[package]
name = "doom-server"
version = "0.1.0"
edition = "2021"

[dependencies]
doom-protocol = { path = "../doom-protocol" }
valence = { git = "https://github.com/Daxanius/valence.git", branch = "main", features = [
    "inventory",
    "network",
    "player_list",
] }
postcard = { version = "1.0", features = ["alloc"] }
mpsc = "0.2.6"
async-trait = "0.1.89"
