[package]
name = "doom-server"
version = "0.1.0"
edition = "2021"

[dependencies]
doom-protocol = { path = "../doom-protocol" }
valence = { version = "0.2.0-alpha.1+mc.1.20.1", features = [
    "inventory",
    "network",
] }
postcard = { version = "1.0", features = ["alloc"] }
mpsc = "0.2.6"
async-trait = "0.1.89"
