use std::{env, fs, path::PathBuf};

// Maps DOOMs PLAYPAL color palette to Minecrafts map palette.
// https://doom.fandom.com/wiki/PLAYPAL
// https://minecraft.fandom.com/wiki/Map_item_format
fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let assets_dir = manifest_dir.join("assets");

    let doom_path = assets_dir.join("playpal.hex");
    let mc_path = assets_dir.join("mc_map.hex");

    println!("cargo:rerun-if-changed={}", doom_path.display());
    println!("cargo:rerun-if-changed={}", mc_path.display());

    let mut doom = parse_hex_palette(&fs::read_to_string(&doom_path).unwrap());
    let mc = parse_hex_palette(&fs::read_to_string(&mc_path).unwrap());

    assert!(
        !mc.is_empty(),
        "Minecraft map palette is empty: {}",
        mc_path.display()
    );

    // We want 256 Doom indices, even if your file is incomplete for now.
    // Set STRICT=1 to force exact 256.
    let strict = env::var("PALETTE_STRICT").ok().as_deref() == Some("1");

    if doom.len() != 256 {
        if strict {
            panic!(
                "Doom palette must have exactly 256 colors, got {} (set PALETTE_STRICT=0 to allow padding)",
                doom.len()
            );
        } else {
            println!(
                "cargo:warning=Doom palette has {} colors, padding to 256 with black (this will NOT match real PLAYPAL indices).",
                doom.len()
            );
            doom.truncate(256);
            while doom.len() < 256 {
                doom.push((0, 0, 0));
            }
        }
    }

    // Compute mapping using linear RGB distance (looks better than naive sRGB)
    let mapping = compute_mapping_linear_rgb(&doom, &mc);

    // Emit Rust source into OUT_DIR
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_path = out_dir.join("palette_mapping.rs");

    let rust = format_rust_u8_array("PALETTE_MAPPING", 256, &mapping);
    fs::write(&out_path, rust).unwrap();

    println!("cargo:warning=Generated {}", out_path.display());
}

fn parse_hex_palette(string: &str) -> Vec<(u8, u8, u8)> {
    let mut out = Vec::new();
    for line in string.lines() {
        let mut t = line.trim();
        if t.is_empty() || t.starts_with("//") || t.starts_with(';') {
            continue;
        }
        if t.starts_with('#') {
            t = &t[1..];
        }
        if t.len() < 6 {
            continue;
        }
        let r = u8::from_str_radix(&t[0..2], 16).unwrap();
        let g = u8::from_str_radix(&t[2..4], 16).unwrap();
        let b = u8::from_str_radix(&t[4..6], 16).unwrap();
        out.push((r, g, b));
    }
    out
}

fn dist2_oklab(a: (u8, u8, u8), b: (u8, u8, u8)) -> f32 {
    let c1 = oklab::srgb_to_oklab([a.0, a.1, a.2].into());
    let c2 = oklab::srgb_to_oklab([b.0, b.1, b.2].into());

    let dl = c1.l - c2.l;
    let da = c1.a - c2.a;
    let db = c1.b - c2.b;

    dl * dl + da * da + db * db
}

fn compute_mapping_linear_rgb(doom: &[(u8, u8, u8)], mc: &[(u8, u8, u8)]) -> Vec<u8> {
    let mut mapping = Vec::with_capacity(doom.len());
    for &dc in doom {
        let mut best_j = 0usize;
        let mut best_d = f32::INFINITY;
        for (j, &mc_c) in mc.iter().enumerate() {
            let d = dist2_oklab(dc, mc_c);
            if d < best_d {
                best_d = d;
                best_j = j;
            }
        }

        mapping.push(best_j.min(255) as u8);
    }
    mapping
}

fn format_rust_u8_array(name: &str, expected_len: usize, vals: &[u8]) -> String {
    assert_eq!(vals.len(), expected_len);

    let mut s = String::from(&format!(
        "// @generated by build.rs\n#[rustfmt::skip]\npub const {name}: [u8; {expected_len}] = [\n"
    ));

    for row in 0..(expected_len / 16) {
        let start = row * 16;
        let end = start + 16;
        s.push_str("    ");
        for (i, v) in vals[start..end].iter().enumerate() {
            if i != 0 {
                s.push_str(", ");
            }
            s.push_str(&format!("{v:3}"));
        }
        s.push_str(",\n");
    }

    s.push_str("];\n");
    s
}
